/**
 * 科研绘图模板目录 —— 逐字取自原版 MathModel 渲染层 chunk（index-OYc102qC.js）。
 *
 * 共 95 套模板 / 7 个分类：流程图 5 / 相关性 28 / 分布 7 / 机器学习 22 /
 * 模型评价 7 / 组合图 12 / 空间分析 14。数组顺序即原版「全部」列表的渲染顺序。
 * 缩略图为原版内置 webp 复刻图，已随包放在 `src/renderer/src/assets/gallery/`。
 *
 * 原版用法（见 i18n 字典 galleryPage* 系列键）：
 *   普通模板 → `/mathmodel-figure-templates 在 LaTeX sandbox 中复刻「<标题>」`
 *   流程图模板 → `/paper-diagram 套用内置模板「<key>」…`（灰白论文版 / 彩色演示版 双提示词）
 */

export interface GalleryTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  /** 绘图库（原版 `library` 字段） */
  library: string;
  /** 模板日期（原版 `createdAt` 字段） */
  createdAt: string;
  /** 流程图模板的 paper-diagram 模板 key（仅 category === '流程图'） */
  diagramKey?: string;
  /** 流程图模板绘制对象（仅 category === '流程图'） */
  diagramTopic?: string;
  /** 相对于 assets/gallery 的文件名 */
  image: string;
}

export const GALLERY: GalleryTemplate[] = [
  {
    id: 'diagram-roadmap-5band',
    title: '五带技术路线图',
    description: '竖版五条点线带：提出问题到评价推广',
    category: '流程图',
    tags: ['技术路线', '全文概览', 'draw.io'],
    library: 'draw.io（paper-diagram）',
    createdAt: '2026-08-17',
    diagramKey: 'roadmap-5band',
    diagramTopic: '整体技术路线图',
    image: 'diagram-roadmap-5band.webp',
  },
  {
    id: 'diagram-roadmap-3phase',
    title: '三阶段问题驱动路线图',
    description: '数据指标、双组建模预测与情景路径规划',
    category: '流程图',
    tags: ['技术路线', '问题驱动', 'draw.io'],
    library: 'draw.io（paper-diagram）',
    createdAt: '2026-08-22',
    diagramKey: 'roadmap-3phase',
    diagramTopic: '三阶段问题驱动技术路线图',
    image: 'diagram-roadmap-3phase.webp',
  },
  {
    id: 'diagram-framework-3col',
    title: '三栏研究框架图',
    description: '左阶段链、中研究内容块、右方法清单',
    category: '流程图',
    tags: ['研究框架', '三栏', 'draw.io'],
    library: 'draw.io（paper-diagram）',
    createdAt: '2026-08-17',
    diagramKey: 'framework-3col',
    diagramTopic: '研究框架图',
    image: 'diagram-framework-3col.webp',
  },
  {
    id: 'diagram-stageflow-3col',
    title: '三栏阶段流程图',
    description: '分层标题条、决策分支和成果分发',
    category: '流程图',
    tags: ['执行流程', '决策分支', 'draw.io'],
    library: 'draw.io（paper-diagram）',
    createdAt: '2026-08-17',
    diagramKey: 'stageflow-3col',
    diagramTopic: '阶段流程图',
    image: 'diagram-stageflow-3col.webp',
  },
  {
    id: 'diagram-taskflow-land',
    title: '横版任务流水线图',
    description: '任务块内流水线，每步挂做法细节',
    category: '流程图',
    tags: ['任务分解', '横版', 'draw.io'],
    library: 'draw.io（paper-diagram）',
    createdAt: '2026-08-17',
    diagramKey: 'taskflow-land',
    diagramTopic: '任务流水线图',
    image: 'diagram-taskflow-land.webp',
  },
  {
    id: 'multiclass-shap-combo',
    title: '多分类 SHAP 组合图',
    description: '堆叠重要性柱状图 + 多类别蜂群图',
    category: '机器学习',
    tags: ['SHAP', '多分类', '蜂群'],
    library: 'matplotlib + shap',
    createdAt: '2026-07-01',
    image: 'multiclass-shap-combo.webp',
  },
  {
    id: 'paired-raincloud',
    title: '配对云雨图',
    description: '半边小提琴、散点、箱线图和均值连线',
    category: '分布',
    tags: ['云雨图', '箱线图', '均值趋势'],
    library: 'matplotlib + ptitprince',
    createdAt: '2026-06-28',
    image: 'paired-raincloud.webp',
  },
  {
    id: 'cv-roc-ci',
    title: '交叉验证 ROC',
    description: '多模型 ROC 曲线、AUC 和置信区间',
    category: '机器学习',
    tags: ['ROC', '交叉验证', 'AUC'],
    library: 'matplotlib + scikit-learn',
    createdAt: '2026-06-30',
    image: 'cv-roc-ci.webp',
  },
  {
    id: 'taylor-diagram',
    title: '多模型泰勒图',
    description: '相关性、标准差和观测点对比',
    category: '模型评价',
    tags: ['Taylor', '回归评价', '相关性'],
    library: 'matplotlib',
    createdAt: '2026-07-03',
    image: 'taylor-diagram.webp',
  },
  {
    id: 'correlation-pairgrid',
    title: '相关矩阵组合图',
    description: '分布、拟合线、置信区间和相关系数',
    category: '相关性',
    tags: ['相关性', 'PairGrid', '热图'],
    library: 'matplotlib + seaborn',
    createdAt: '2026-06-25',
    image: 'correlation-pairgrid.webp',
  },
  {
    id: 'prediction-marginal-grid',
    title: '预测-真实边缘图',
    description: '散点主图、边缘直方图和 KDE 曲线',
    category: '模型评价',
    tags: ['回归', 'Pred vs True', 'KDE'],
    library: 'matplotlib + seaborn',
    createdAt: '2026-07-04',
    image: 'prediction-marginal-grid.webp',
  },
  {
    id: 'rf-tpe-surface',
    title: 'TPE 调参 3D 曲面',
    description: 'RF 超参数搜索曲面和 RMSE 色带',
    category: '机器学习',
    tags: ['Optuna', 'Random Forest', '3D'],
    library: 'matplotlib + optuna',
    createdAt: '2026-07-02',
    image: 'rf-tpe-surface.webp',
  },
  {
    id: 'grouped-corr-split-violin',
    title: '相关矩阵 + 半边小提琴',
    description: '特征分组相关矩阵和分布对比',
    category: '分布',
    tags: ['相关矩阵', '特征分组', '小提琴'],
    library: 'matplotlib + seaborn',
    createdAt: '2026-06-29',
    image: 'grouped-corr-split-violin.webp',
  },
  {
    id: 'grouped-circular-heatmap',
    title: '分组环形热图',
    description: '多环热图、分组色带和径向标签',
    category: '相关性',
    tags: ['环形热图', '分组', '极坐标'],
    library: 'matplotlib',
    createdAt: '2026-06-27',
    image: 'grouped-circular-heatmap.webp',
  },
  {
    id: 'urban-park-cooling-combo',
    title: '堆叠图 + 云雨图 + 箱线图',
    description: '城市公园数量和降温指标组合面板',
    category: '组合图',
    tags: ['组合图', '城市', '箱线图'],
    library: 'matplotlib + cartopy',
    createdAt: '2026-07-05',
    image: 'urban-park-cooling-combo.webp',
  },
  {
    id: 'nature-chord-diagram',
    title: 'Nature 风格和弦图',
    description: 'Circos 外环分组和半透明连接带',
    category: '相关性',
    tags: ['Chord', 'Circos', 'Nature'],
    library: 'matplotlib',
    createdAt: '2026-06-26',
    image: 'nature-chord-diagram.webp',
  },
  {
    id: 'land-diurnal-lst-maps',
    title: '昼夜地表温度图集',
    description: '昼夜与季节地图、温度分级和分布曲线',
    category: '空间分析',
    tags: ['地表温度', '昼夜对比', '空间分布'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-11',
    image: 'land-diurnal-lst-maps.webp',
  },
  {
    id: 'land-morphology-lst-linear',
    title: '城市形态-地温线性图',
    description: '多季节散点、线性拟合和置信区间小多图',
    category: '相关性',
    tags: ['城市形态', '线性关系', '小多图'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-11',
    image: 'land-morphology-lst-linear.webp',
  },
  {
    id: 'land-morphology-lst-nonlinear',
    title: '城市形态-地温非线性图',
    description: '多季节非线性响应曲线和不确定性带',
    category: '相关性',
    tags: ['城市形态', '非线性', '响应曲线'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-11',
    image: 'land-morphology-lst-nonlinear.webp',
  },
  {
    id: 'land-diurnal-feature-importance',
    title: '昼夜特征重要性气泡图',
    description: '昼夜分组、双重编码和季节对比',
    category: '机器学习',
    tags: ['特征重要性', '气泡图', '昼夜对比'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-11',
    image: 'land-diurnal-feature-importance.webp',
  },
  {
    id: 'land-shap-interactions',
    title: '多面板 SHAP 交互图',
    description: '特征依赖、交互着色和零线对照',
    category: '机器学习',
    tags: ['SHAP', '交互效应', '依赖图'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-11',
    image: 'land-shap-interactions.webp',
  },
  {
    id: 'land-model-prediction-comparison',
    title: '多模型预测对比图',
    description: '训练/测试时序对比和模型指标',
    category: '模型评价',
    tags: ['模型对比', '训练测试', '预测'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-11',
    image: 'land-model-prediction-comparison.webp',
  },
  {
    id: 'sr-weather-model-evaluation-map',
    title: '气象模型空间评估图',
    description: 'RMSE、R²、MBE 的多模型空间对比',
    category: '空间分析',
    tags: ['气象', '空间评估', '多模型'],
    library: 'matplotlib + cartopy',
    createdAt: '2026-08-11',
    image: 'sr-weather-model-evaluation-map.webp',
  },
  {
    id: 'sr-weather-downscaling-map',
    title: '四季气温降尺度地图',
    description: '约 25 km 到 1 km 的多模型降尺度对比',
    category: '空间分析',
    tags: ['降尺度', '气温', '超分辨率'],
    library: 'matplotlib + cartopy',
    createdAt: '2026-08-11',
    image: 'sr-weather-downscaling-map.webp',
  },
  {
    id: 'karst-es-sdg-sankey',
    title: '生态系统服务-SDG 桑基图',
    description: '服务类型、SDG target 与目标三层流向',
    category: '组合图',
    tags: ['桑基图', '生态系统服务', 'SDG'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-11',
    image: 'karst-es-sdg-sankey.webp',
  },
  {
    id: 'karst-land-use-scenarios',
    title: '喀斯特土地利用情景图',
    description: '三种 SSP 情景地图与局部放大',
    category: '空间分析',
    tags: ['土地利用', 'SSP', '情景模拟'],
    library: 'matplotlib + scipy',
    createdAt: '2026-08-11',
    image: 'karst-land-use-scenarios.webp',
  },
  {
    id: 'karst-ecosystem-services-atlas',
    title: '生态系统服务情景图集',
    description: '历史年份与 2035 情景的四类服务地图',
    category: '空间分析',
    tags: ['生态系统服务', '情景预测', '地图图集'],
    library: 'matplotlib + scipy',
    createdAt: '2026-08-11',
    image: 'karst-ecosystem-services-atlas.webp',
  },
  {
    id: 'karst-es-hotspot-scenarios',
    title: '生态服务冷热点情景图',
    description: '总服务指数与 Getis–Ord Gi* 冷热点对照',
    category: '空间分析',
    tags: ['冷热点', 'Getis-Ord', '空间统计'],
    library: 'matplotlib + scipy',
    createdAt: '2026-08-11',
    image: 'karst-es-hotspot-scenarios.webp',
  },
  {
    id: 'esv-grid-zone-scenarios',
    title: '生态服务价值分级格网图',
    description: '1990–2020 四期五级格网空间分布',
    category: '空间分析',
    tags: ['ESV', '格网', '时序地图'],
    library: 'matplotlib + scipy',
    createdAt: '2026-08-20',
    image: 'esv-grid-zone-scenarios.webp',
  },
  {
    id: 'esv-local-moran-scenarios',
    title: '局部 Moran 聚类地图',
    description: '四期高高、低低与空间离群聚类',
    category: '空间分析',
    tags: ['Local Moran', 'LISA', '空间聚类'],
    library: 'matplotlib + scipy',
    createdAt: '2026-08-20',
    image: 'esv-local-moran-scenarios.webp',
  },
  {
    id: 'landslide-shap-decision-heatmaps',
    title: 'SHAP 决策热图',
    description: '双组决策热图、模型输出和重要性条',
    category: '机器学习',
    tags: ['SHAP', '决策热图', '可解释性'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-21',
    image: 'landslide-shap-decision-heatmaps.webp',
  },
  {
    id: 'landslide-pdp-interaction-grid',
    title: 'PDP 交互等值图',
    description: '单变量响应曲线与双变量交互等值面',
    category: '机器学习',
    tags: ['PDP', '交互效应', '等值图'],
    library: 'matplotlib + scipy',
    createdAt: '2026-08-21',
    image: 'landslide-pdp-interaction-grid.webp',
  },
  {
    id: 'biodiversity-global-delta-atlas',
    title: '全球差异分布图集',
    description: '全球分级地图、纬向剖面与 KDE 分布',
    category: '空间分析',
    tags: ['全球地图', '纬向剖面', 'KDE'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-21',
    image: 'biodiversity-global-delta-atlas.webp',
  },
  {
    id: 'biodiversity-global-correlation-atlas',
    title: '全球相关性图集',
    description: '全球相关地图、纬向剖面与分区系数',
    category: '空间分析',
    tags: ['全球地图', '相关性', '分区回归'],
    library: 'matplotlib + numpy',
    createdAt: '2026-08-21',
    image: 'biodiversity-global-correlation-atlas.webp',
  },
  {
    id: 'principal-coordinate-map',
    title: '主坐标排序与边缘密度图',
    description: '中央排序散点与椭圆；顶部和右侧平滑密度；图内分组图例',
    category: '相关性',
    tags: ['PCoA', '排序分析', '边缘密度'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'principal-coordinate-map.webp',
  },
  {
    id: 'redundancy-ordination',
    title: '多编码约束排序图',
    description: '单排序面板；10支变量箭头；颜色、形状、大小三组独立图例',
    category: '相关性',
    tags: ['RDA', '约束排序', '多重编码'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'redundancy-ordination.webp',
  },
  {
    id: 'pca-association-network',
    title: '三角相关矩阵与主成分连线图',
    description: '三角方块相关矩阵与四个主成分节点在同一画布连接；左侧色标及线宽图例',
    category: '相关性',
    tags: ['PCA', '相关矩阵', '关联网络'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'pca-association-network.webp',
  },
  {
    id: 'circular-ranking-bars',
    title: '同心圆弧排名图',
    description: '九条同心圆弧；起点类别、弧内数值与外围角度刻度',
    category: '组合图',
    tags: ['排名', '圆弧', '比例'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'circular-ranking-bars.webp',
  },
  {
    id: 'horizontal-share-bars',
    title: '横向组成比例与连接带图',
    description: '六条横向百分比堆叠；分区数值、行间连接带和右侧图例',
    category: '组合图',
    tags: ['组成比例', '堆叠条', '连接带'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'horizontal-share-bars.webp',
  },
  {
    id: 'polar-area-panels',
    title: '九宫格径向扇区分布图',
    description: '3×3九个径向扇区面板；每图14类、百分比外标和逐图色阶图例',
    category: '分布',
    tags: ['极坐标', '扇区', '多面板'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'polar-area-panels.webp',
  },
  {
    id: 'radial-stacked-sectors',
    title: '多对象径向堆叠柱图',
    description: '22对象径向堆叠柱；22组成分量、外侧标签、径向刻度与完整颜色图例',
    category: '组合图',
    tags: ['径向柱', '组成比例', '多对象'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'radial-stacked-sectors.webp',
  },
  {
    id: 'ribbon-trajectories-3d',
    title: '多组年度三维条带图',
    description: '八组逐年有宽度的三维折线条带；三维网格、组名及内置颜色图例',
    category: '组合图',
    tags: ['三维条带', '年度变化', '多组对比'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'ribbon-trajectories-3d.webp',
  },
  {
    id: 'waterfall-density-3d',
    title: '多组多阶段三维瀑布峰图',
    description: '四组配色、每组三阶段共12条瀑布峰；透明填充、阶段标注和图例',
    category: '分布',
    tags: ['三维密度', '瀑布峰', '多阶段'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'waterfall-density-3d.webp',
  },
  {
    id: 'layered-heatmaps-3d',
    title: '四层三维矩阵热图',
    description: '四层独立热图平面；三维透视、层级标签和共享色标',
    category: '组合图',
    tags: ['三维热图', '分层矩阵', '色标'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'layered-heatmaps-3d.webp',
  },
  {
    id: 'column-grid-3d',
    title: '规则矩阵三维柱图',
    description: '10×10三维柱阵；高度与颜色双编码、三轴刻度和独立色标',
    category: '组合图',
    tags: ['三维柱', '矩阵', '数值对比'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'column-grid-3d.webp',
  },
  {
    id: 'violin-mean-trends',
    title: '六面板分组小提琴均值矩阵',
    description: '2×3六面板；每图九组小提琴与箱体；共用连续色标',
    category: '分布',
    tags: ['小提琴', '均值', '分组分布'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'violin-mean-trends.webp',
  },
  {
    id: 'rank-distribution-test',
    title: '两组半小提琴箱线散点检验图',
    description: '单面板；向外半小提琴、箱体与原始散点叠加；真实检验显著性横线',
    category: '分布',
    tags: ['半小提琴', '箱线图', '秩检验'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'rank-distribution-test.webp',
  },
  {
    id: 'polar-estimate-intervals',
    title: '分区径向分组均值与误差图',
    description: '八个环形分区各四组柱与置信区间；外圈分类色带、数值刻度和中心图例',
    category: '组合图',
    tags: ['极坐标', '均值', '置信区间'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'polar-estimate-intervals.webp',
  },
  {
    id: 'surface-projection-3d',
    title: '三维响应面与等值底图',
    description: '独立三维线框响应面；底部连续等值投影；竖向色标和完整变量轴',
    category: '组合图',
    tags: ['三维曲面', '等值线', '响应面'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'surface-projection-3d.webp',
  },
  {
    id: 'set-overlap-report',
    title: '四情景集合交叠与贡献条图',
    description: '2×2四组集合交叠图；外部全集边界、七交集计数、图旁集合图例和底部分类色卡',
    category: '组合图',
    tags: ['集合交叠', '情景对比', '交集计数'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'set-overlap-report.webp',
  },
  {
    id: 'importance-association-report',
    title: '变量重要性与稀疏相关气泡矩阵',
    description: '40×26稀疏显著性气泡矩阵；26项顶部重要性柱、相关色标和点大小图例',
    category: '相关性',
    tags: ['变量重要性', '相关气泡', '显著性'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'importance-association-report.webp',
  },
  {
    id: 'time-regression-matrix',
    title: '四变量相关矩阵与年度趋势组合图',
    description: '左侧4×4相关矩阵：直方密度、散点拟合和统计色块；右侧四层年度回归',
    category: '相关性',
    tags: ['相关矩阵', '年度趋势', '回归'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'time-regression-matrix.webp',
  },
  {
    id: 'lollipop-effect-grid',
    title: '分层标准化回归系数图',
    description: '三类模型各三项系数；分组背景、点大小、虚线连接和右侧图例',
    category: '模型评价',
    tags: ['回归系数', '分层模型', '效应比较'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'lollipop-effect-grid.webp',
  },
  {
    id: 'circular-effect-intervals',
    title: '环形标准化与原始效应比较图',
    description: '四簇共12因素；成对环形柱、误差棒、系数环线及底部图例',
    category: '模型评价',
    tags: ['效应估计', '环形柱', '误差棒'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'circular-effect-intervals.webp',
  },
  {
    id: 'correlation-glyph-grid',
    title: '椭圆相关与显著性数字矩阵',
    description: '16变量完整矩阵；下三角相关椭圆、上三角数值及显著性、对角变量名',
    category: '相关性',
    tags: ['相关椭圆', '显著性', '相关矩阵'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'correlation-glyph-grid.webp',
  },
  {
    id: 'association-network-heatmap',
    title: '三组相关矩阵与中心响应连线图',
    description: '三个角落的三角相关矩阵；中心响应节点与跨面板连线；独立图例和色标',
    category: '相关性',
    tags: ['相关网络', '三角热图', '多组对比'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'association-network-heatmap.webp',
  },
  {
    id: 'split-cohort-correlation',
    title: '双变量同步性三角分割矩阵',
    description: '15区域下三角；每格两种条件的半格三角形；分歧色标及双条件坐标标题',
    category: '相关性',
    tags: ['分组相关', '三角分割', '同步性'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'split-cohort-correlation.webp',
  },
  {
    id: 'regression-uncertainty-scatter',
    title: '误差棒回归与连续着色散点图',
    description: '15个误差棒散点；负向回归、零线、右上统计和图内横向连续色标',
    category: '相关性',
    tags: ['回归', '误差棒', '连续着色'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'regression-uncertainty-scatter.webp',
  },
  {
    id: 'fdr-association-map',
    title: '多重检验相关三角热图',
    description: '13变量下三角相关色块；每格相关值和FDR显著性；图内显著性图例',
    category: '相关性',
    tags: ['FDR', '相关热图', '多重检验'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'fdr-association-map.webp',
  },
  {
    id: 'grouped-block-correlation',
    title: '分组矩形相关矩阵与排序色带',
    description: '20×14分组相关矩阵；左侧三类分组条、顶部色标和逐格显著性',
    category: '相关性',
    tags: ['分组矩阵', '排序色带', '显著性'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'grouped-block-correlation.webp',
  },
  {
    id: 'cohort-correlation-bubbles',
    title: '四区域多变量相关气泡图',
    description: '四行20变量气泡；大小编码相关强度、颜色编码正负、显著性透明度及侧图例',
    category: '相关性',
    tags: ['气泡图', '区域对比', '相关强度'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'cohort-correlation-bubbles.webp',
  },
  {
    id: 'interaction-bubble-grid',
    title: '因子交互气泡与数字矩阵',
    description: '11×11矩阵；上三角变径气泡、下三角数值、因子标签及统一色标',
    category: '相关性',
    tags: ['因子关联', '气泡矩阵', '相关系数'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'interaction-bubble-grid.webp',
  },
  {
    id: 'distance-association-network',
    title: '距离关联网络与三角矩阵',
    description: '18变量三角方块矩阵；四个右侧距离关联节点；变线宽曲线及色标',
    category: '相关性',
    tags: ['Mantel', '距离关联', '三角矩阵'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'distance-association-network.webp',
  },
  {
    id: 'grouped-scatter-matrix',
    title: '分组相关散点与边缘分布矩阵',
    description: '5×5组合：4×4分组相关矩阵、右侧四组小提琴、底部四幅直方图及计数柱',
    category: '相关性',
    tags: ['分组散点', '边缘分布', '相关矩阵'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'grouped-scatter-matrix.webp',
  },
  {
    id: 'pearson-correlation-map',
    title: '长变量列表稀疏相关矩阵',
    description: '30行8列窄长方格矩阵；显著相关方块、顶部斜标签与长行名',
    category: '相关性',
    tags: ['Pearson', '稀疏矩阵', '长变量列表'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'pearson-correlation-map.webp',
  },
  {
    id: 'petal-correlation-panels',
    title: '四分区扇形相关热图',
    description: '四个独立扇形三角相关分区；逐格显著性、外围变量标签、中央图例和底部色标',
    category: '相关性',
    tags: ['扇形热图', '分区相关', '显著性'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'petal-correlation-panels.webp',
  },
  {
    id: 'grouped-regression-marginals',
    title: '双组回归散点与平滑边缘密度',
    description: '金绿双组密集回归散点；顶部与右侧密度；两处组别拟合统计',
    category: '相关性',
    tags: ['分组回归', '边缘密度', '拟合统计'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'grouped-regression-marginals.webp',
  },
  {
    id: 'scatter-network-report',
    title: '散点上三角与外部关联网络',
    description: '右上5×5散点三角矩阵；对角因子标签；左侧四节点网络及分组图例',
    category: '相关性',
    tags: ['散点矩阵', '关联网络', '组合图'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'scatter-network-report.webp',
  },
  {
    id: 'network-profile-report',
    title: '相关网络与共线性径向报告',
    description: '左三角相关矩阵连接目标节点；右十一变量径向VIF柱图；完整标签与色标',
    category: '相关性',
    tags: ['相关网络', '共线性', '径向报告'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'network-profile-report.webp',
  },
  {
    id: 'attribution-matrix-summary',
    title: '特征贡献热图与汇总条形图',
    description: '样本与特征贡献矩阵，搭配平均绝对贡献条形排名',
    category: '机器学习',
    tags: ['特征贡献', '热图', '汇总排名'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'attribution-matrix-summary.webp',
  },
  {
    id: 'attribution-waterfall',
    title: '单样本贡献瀑布图',
    description: '十特征单样本瀑布；红蓝箭头条、贡献值、特征取值、基准值和最终预测',
    category: '机器学习',
    tags: ['单样本解释', '瀑布图', '基准值'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'attribution-waterfall.webp',
  },
  {
    id: 'grouped-attribution-importance',
    title: '分组贡献条形与蜂群联合图',
    description: '17行分组重要性条与蜂群共用排序；顶部浅色标题带、底部横色标和三类指标图例',
    category: '机器学习',
    tags: ['特征贡献', '蜂群图', '分组排名'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'grouped-attribution-importance.webp',
  },
  {
    id: 'attribution-top-feature-report',
    title: '特征贡献排名与六项依赖图',
    description: '左19特征贡献条；右2×3六个贡献依赖散点、平滑拟合与置信带',
    category: '机器学习',
    tags: ['贡献排名', '依赖图', '特征解释'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'attribution-top-feature-report.webp',
  },
  {
    id: 'attribution-polar-importance',
    title: '镜像贡献排名蜂群与径向占比图',
    description: '20特征镜像排名条与蜂群；左下径向占比插图；红蓝渐变及右侧色标',
    category: '机器学习',
    tags: ['蜂群图', '镜像排名', '径向占比'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'attribution-polar-importance.webp',
  },
  {
    id: 'smooth-effect-residual-report',
    title: '十六面板平滑响应等值图',
    description: '4×4十六等值面板；统一棕白青色标、白色实虚等值线和每图计算指标',
    category: '机器学习',
    tags: ['平滑响应', '等值线', '多面板'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'smooth-effect-residual-report.webp',
  },
  {
    id: 'attribution-threshold-report',
    title: '九因子阈值与正负贡献图',
    description: '3×3九个阈值图；正负区域填色、蓝色拟合置信带、红色零交点与每图统计',
    category: '机器学习',
    tags: ['特征贡献', '零交点', '正负响应'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'attribution-threshold-report.webp',
  },
  {
    id: 'interaction-network',
    title: '密集特征交互环形网络',
    description: '18节点完整环网；交互强度控制边色和线宽、节点重要性控制颜色与大小；双独立色标',
    category: '机器学习',
    tags: ['特征交互', '环形网络', '连接强度'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'interaction-network.webp',
  },
  {
    id: 'attribution-intervals',
    title: '多特征贡献均值区间排名图',
    description: '30特征窄长区间图；逐项不同颜色、均值点与横向置信区间、零参考线',
    category: '机器学习',
    tags: ['贡献均值', '置信区间', '特征排名'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'attribution-intervals.webp',
  },
  {
    id: 'multiresponse-effect-curves',
    title: '四响应贡献回归叠加图',
    description: '四响应单面板叠加；散点、非线性拟合及置信带；调整R²和底部分类图例',
    category: '机器学习',
    tags: ['多响应', '贡献回归', '效应曲线'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'multiresponse-effect-curves.webp',
  },
  {
    id: 'pixel-regression-maps',
    title: '像元主导因子分类图',
    description: '单幅细密像元主导因子图；四个离散类别及逐类色标',
    category: '空间分析',
    tags: ['像元分类', '主导因子', '网格'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'pixel-regression-maps.webp',
  },
  {
    id: 'moving-window-partial-correlation',
    title: '空间网格偏相关热图',
    description: '单幅空间偏相关栅格；实际控制变量残差相关计算；固定[-1,1]色标',
    category: '空间分析',
    tags: ['偏相关', '时间序列', '网格热图'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'moving-window-partial-correlation.webp',
  },
  {
    id: 'spatial-attribution-maps',
    title: '不规则区域主导特征图',
    description: '白色画布上的不规则区域像元图；两个主导特征类别、区域外掩膜及色标',
    category: '空间分析',
    tags: ['空间贡献', '主导特征', '区域掩膜'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'spatial-attribution-maps.webp',
  },
  {
    id: 'dual-axis-time-comparison',
    title: '充放电功率与储能时序图',
    description: '24小时正负渐变功率柱；红色储能折线和右轴；储能由功率累计计算',
    category: '组合图',
    tags: ['功率', '储能', '双轴时序'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'dual-axis-time-comparison.webp',
  },
  {
    id: 'pca-variance-report',
    title: 'PCA 主成分与方差解释报告',
    description: '主成分得分、变量载荷、碎石图与累计解释方差',
    category: '相关性',
    tags: ['PCA', '变量载荷', '解释方差'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'pca-variance-report.webp',
  },
  {
    id: 'clustered-rank-correlation',
    title: '双向层次聚类相关热图',
    description: '24×14矩形秩相关热图；独立行列聚类树、显著性标记、变量标签和色标',
    category: '相关性',
    tags: ['层次聚类', '秩相关', '双向聚类'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'clustered-rank-correlation.webp',
  },
  {
    id: 'ternary-composition',
    title: '三元组成与连续变量气泡图',
    description: '三元比例定位，气泡大小与连续色标展示附加变量',
    category: '分布',
    tags: ['三元组成', '气泡图', '连续变量'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'ternary-composition.webp',
  },
  {
    id: 'ranked-feature-heatmap',
    title: '排名柱形与贡献热图联合报告',
    description: '上方18项排名柱图与环图；13×18矩阵及右侧两列汇总数值',
    category: '机器学习',
    tags: ['特征排名', '贡献热图', '组合报告'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'ranked-feature-heatmap.webp',
  },
  {
    id: 'radial-cohort-dashboard',
    title: '多队列密集环形评价图',
    description: '160对象十层同心热图；外圈分类色带、对象文字、外圈数值柱与中心图例',
    category: '模型评价',
    tags: ['多队列', '环形指标', '综合评价'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'radial-cohort-dashboard.webp',
  },
  {
    id: 'model-marginal-comparison',
    title: '六模型预测边缘分布与残差矩阵',
    description: '2×3六模型；每图完整预测散点、顶部渐变直方图、右侧直方图及底部残差条',
    category: '模型评价',
    tags: ['预测评价', '边缘分布', '残差'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'model-marginal-comparison.webp',
  },
  {
    id: 'circular-correlation-rings',
    title: '分组相关系数环形热图',
    description: '24因子五层相关数值热环；内圈分组色带、中心图例、外圈名称及开口',
    category: '相关性',
    tags: ['环形热图', '分组相关', '多指标'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'circular-correlation-rings.webp',
  },
  {
    id: 'effect-marginal-panel-grid',
    title: '十五因子效应与底部直方图矩阵',
    description: '3×5十五个效应面板；每图底部直方图、拟合置信带、实际零交点与阈值标注',
    category: '机器学习',
    tags: ['效应曲线', '边缘直方图', '多因子'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'effect-marginal-panel-grid.webp',
  },
  {
    id: 'conditional-effect-histogram',
    title: '条件贡献回归与背景分布图',
    description: '背景直方图与彩色贡献散点；两条件回归及置信带、双轴和色标',
    category: '机器学习',
    tags: ['条件贡献', '回归', '背景分布'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'conditional-effect-histogram.webp',
  },
  {
    id: 'attribution-dependence-report',
    title: '贡献蜂群与六变量阈值依赖报告',
    description: '19特征蜂群叠加灰色重要性条；右侧3×2彩色依赖图，每图阈值、中位线和色标',
    category: '机器学习',
    tags: ['贡献蜂群', '依赖图', '零交点'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'attribution-dependence-report.webp',
  },
  {
    id: 'response-contour-matrix',
    title: '六对变量响应等值面板',
    description: '2×3六变量对响应等值图；每图等值线数值、坐标名和独立连续色标',
    category: '机器学习',
    tags: ['变量响应', '等值面', '双变量'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'response-contour-matrix.webp',
  },
  {
    id: 'spatial-attribution-summary',
    title: '分区长列表贡献分布图',
    description: '30行空间分组贡献散点；长标签、零线、分组分隔线和连续色标',
    category: '空间分析',
    tags: ['区域贡献', '分布比较', '特征排名'],
    library: 'matplotlib + numpy + scipy',
    createdAt: '2026-09-10',
    image: 'spatial-attribution-summary.webp',
  },
]

/**
 * 数学建模首选目录。
 *
 * 目录不是“越多越好”：演示和论文入口只展示能直接支撑建模论证的图，
 * 其余旧模板仍留在数据文件中供历史项目读取，但不再污染新任务的选择器。
 */
export const MATHMODEL_GALLERY_IDS = new Set<string>([
  'diagram-roadmap-5band',
  'diagram-roadmap-3phase',
  'diagram-framework-3col',
  'diagram-stageflow-3col',
  'diagram-taskflow-land',
  'principal-coordinate-map',
  'redundancy-ordination',
  'pca-association-network',
  'horizontal-share-bars',
  'set-overlap-report',
  'time-regression-matrix',
  'regression-uncertainty-scatter',
  'grouped-block-correlation',
  'correlation-pairgrid',
  'grouped-regression-marginals',
  'attribution-matrix-summary',
  'attribution-waterfall',
  'attribution-intervals',
  'multiresponse-effect-curves',
  'spatial-attribution-maps',
  'dual-axis-time-comparison',
  'pca-variance-report',
  'clustered-rank-correlation',
  'ternary-composition',
  'paired-raincloud',
  'cv-roc-ci',
  'taylor-diagram',
  'prediction-marginal-grid',
  'grouped-corr-split-violin',
  'land-model-prediction-comparison',
  'landslide-pdp-interaction-grid',
  'esv-local-moran-scenarios',
  'response-contour-matrix',
]);

export const MATHMODEL_GALLERY: GalleryTemplate[] = GALLERY.filter((item) =>
  MATHMODEL_GALLERY_IDS.has(item.id),
);

/** 首选目录分类（保持稳定顺序，便于演示时快速筛选） */
export const GALLERY_CATEGORIES: string[] = [
  '流程图',
  '相关性',
  '分布',
  '机器学习',
  '模型评价',
  '组合图',
  '空间分析',
].filter((category) => MATHMODEL_GALLERY.some((item) => item.category === category));

/** 绘图主题（原版 `b6e`，默认 mono） */
export const DIAGRAM_THEMES: Array<'mono' | 'color'> = ['mono', 'color'];
export const DEFAULT_DIAGRAM_THEME: 'mono' | 'color' = 'mono';

/** 普通模板：发给 Agent 的复刻指令（逐字取自原版字符串表） */
export function galleryPrompt(title: string): string {
  return `/mathmodel-figure-templates 在 LaTeX sandbox 中复刻「${title}」。请优先调用 skill 内置的 render_template.py 和模板脚本，使用当前数学建模题目中数据绘制，输出 PNG/PDF/SVG，并返回脚本和图片路径。`;
}

/** 流程图模板：`/paper-diagram` 双主题提示词（逐字取自原版 `uM()`） */
export function paperDiagramPrompt(
  templateKey: string,
  topic: string,
  theme: 'mono' | 'color' = DEFAULT_DIAGRAM_THEME,
): string {
  const themeName = theme === 'mono' ? '灰白论文版' : '彩色演示版';
  return `/paper-diagram 套用内置模板「${templateKey}」绘制本题的${topic}。采用「${themeName}」主题，调用对应模板脚本时显式传入 \`--theme ${theme}\`。请从当前题目与已完成的建模内容中提取真实材料填写模板 content JSON，渲染出可编辑 .drawio，再用 check_layout.py 校验、export_figure.py 导出 PNG/PDF，并返回 content JSON、.drawio 和图片路径。`;
}

/** 按模板类型分派提示词：流程图走 paper-diagram，其余走 figure-templates */
export function templatePrompt(item: GalleryTemplate, theme: 'mono' | 'color' = DEFAULT_DIAGRAM_THEME): string {
  if (item.diagramKey && item.diagramTopic) {
    return paperDiagramPrompt(item.diagramKey, item.diagramTopic, theme);
  }
  return galleryPrompt(item.title);
}
